export enum ActionType {
  ON_LOGIN = 'ON_LOGIN',
  ON_ERROR = 'ON_ERROR',

  SET_USER_EMAIL = 'SET_USER_EMAIL',
  SET_USER_PASSWORD = 'SET_USER_PASSWORD',

  SET_EVENT = 'SET_EVENT',
  SET_EVENT_ORGANIZATOR = 'SET_EVENT_ORGANIZATOR',
  SET_EVENT_NUME = 'SET_EVENT_NUME',
  SET_EVENT_DATA = 'SET_EVENT_DATA',
  SET_EVENT_NRPERSOANE = 'SET_EVENT_NRPERSOANE',
  SET_EVENT_IDMENIU = 'SET_EVENT_IDMENIU',
  SET_EVENT_PRET = 'SET_EVENT_PRET',
  SET_EVENT_AVANS = 'SET_EVENT_AVANS',
  SET_EVENT_PLATA = 'SET_EVENT_PLATA',
  SET_EVENT_IMG = 'SER_EVENT_IMG',
  SET_EVENT_UID = 'SET_EVENT_UID',

  SET_EVENTS = 'SET_EVENTS',
  GET_EVENTS = 'GET_EVENTS',
}
